### ISSUE TITLE
can support ejabberd 14.*?

### ISSUE THREAD

**Issue by xoxoj** [Mingism/ejabberd-stanza-ack#6]
Hi,this module can support ejabberd 14.*?

**Comment by arana91** [comment]
Hi,
I compiled this module for 14.07 by removing all the ?INFO_MSG and ?DEBUG statements (apparently not supported) and made a beam file successfully.

Havent been able to debug anything though since the kind of xmpp stanzas come as acknowledgements is not documented.

Anyone aware? Or anybody who could make this work on 14.07?

**Comment by satishck1992** [comment]
Hi I am trying this on 15.06. I have compiled this successfully, but ejabberd keeps throwing error. I am currently debugging it. @arana91  is it working for you ??

**Comment by arana91** [comment]
Hi @satishck1992
I could make it work fine for the ejabberd 14.07
For your version there are a few new changes made by ejabberd and corresponding to those, additions need to be made to the module i guess. I am not aware of the changes exactly. I got this info from Badlop, a guy who contributes to Process One modules. You can locate him for precise info around here on Github too or Process-One forums.
Thanks

**Comment by satishck1992** [comment]
@arana91 
I am currently trying to make it work for 15.06. I will post updates soon.

**Comment by Mingism** [comment]
Thanks for trying to make it work. I am not using ejabberd at this time any
more. Feel free to do a pull request if it works.

From:  satishck1992 <notifications@github.com>
Reply-To:  Mingism/ejabberd-stanza-ack
<reply+001324afee2110b7f50420947ba6c90ba98eb244b909203592cf0000000111cd86c49
2a169ce031ae240@reply.github.com>
Date:  Monday 27 July 2015 07:42
To:  Mingism/ejabberd-stanza-ack <ejabberd-stanza-ack@noreply.github.com>
Subject:  Re: [ejabberd-stanza-ack] can support ejabberd 14.*? (#6)


@arana91 <https://github.com/arana91>
I am currently trying to make it work for 15.06. I will post updates soon.


Reply to this email directly or view it on GitHub
<https://github.com/Mingism/ejabberd-stanza-ack/issues/6#issuecomment-125093
405> .

**Comment by Nitin3588** [comment]
i am using ejabberd 15.07 and  also getting  error while sending ack  ,if you need i can share error log too .

**Comment by Mingism** [comment]
Hi i am no longer supporting this code.

**Comment by Nitin3588** [comment]
can you guide me than how could i route a  packet from my server to client .

**Comment by Mingism** [comment]
I am not familiar with the new ejabberd server so I cannot provide help.

**Comment by satishck1992** [comment]
I have updated the code to support ejabberd 15.06 and opened a pull request.

**Comment by Mingism** [comment]
Merged

**Comment by Nitin3588** [comment]
Thanks for making it. If i a client sent any malformed xml packet , it  acknowledges  them too .that means you are sending ack for  error messages also , while error message are returned  back as type=error which need not to be ack.

**Comment by Mingism** [comment]
Yeah if you want to fix it and make a pull request let me know

Kay

**Comment by satishck1992** [comment]
@Nitin3588 can you give me one of the example stanzas where type = error happens ? Also please attach the relevant xml stanza.

**Comment by satishck1992** [comment]
Hi @Nitin3588  , I have added error filtering in the latest code. I have opened a pull request too.

**Comment by Mingism** [comment]
Merged
